/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PedidoNumeroRouteImport } from './routes/pedido.$numero'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminIgrejasRouteImport } from './routes/admin.igrejas'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin.pedidos.index'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'
import { Route as ApiPublicDocumentoNumeroRouteImport } from './routes/api/public/documento.$numero'
import { Route as ApiAdminComprovantePedidoIdRouteImport } from './routes/api/admin/comprovante.$pedidoId'

const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoNumeroRoute = PedidoNumeroRouteImport.update({
  id: '/pedido/$numero',
  path: '/pedido/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIgrejasRoute = AdminIgrejasRouteImport.update({
  id: '/igrejas',
  path: '/igrejas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const ApiPublicDocumentoNumeroRoute =
  ApiPublicDocumentoNumeroRouteImport.update({
    id: '/api/public/documento/$numero',
    path: '/api/public/documento/$numero',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminComprovantePedidoIdRoute =
  ApiAdminComprovantePedidoIdRouteImport.update({
    id: '/api/admin/comprovante/$pedidoId',
    path: '/api/admin/comprovante/$pedidoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/igrejas': typeof AdminIgrejasRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/api/admin/comprovante/$pedidoId': typeof ApiAdminComprovantePedidoIdRoute
  '/api/public/documento/$numero': typeof ApiPublicDocumentoNumeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/igrejas': typeof AdminIgrejasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/api/admin/comprovante/$pedidoId': typeof ApiAdminComprovantePedidoIdRoute
  '/api/public/documento/$numero': typeof ApiPublicDocumentoNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/igrejas': typeof AdminIgrejasRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/api/admin/comprovante/$pedidoId': typeof ApiAdminComprovantePedidoIdRoute
  '/api/public/documento/$numero': typeof ApiPublicDocumentoNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/meus-pedidos'
    | '/admin/estoque'
    | '/admin/igrejas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$numero'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/'
    | '/api/admin/comprovante/$pedidoId'
    | '/api/public/documento/$numero'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/meus-pedidos'
    | '/admin/estoque'
    | '/admin/igrejas'
    | '/admin/produtos'
    | '/pedido/$numero'
    | '/admin'
    | '/admin/pedidos/$id'
    | '/admin/pedidos'
    | '/api/admin/comprovante/$pedidoId'
    | '/api/public/documento/$numero'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/meus-pedidos'
    | '/admin/estoque'
    | '/admin/igrejas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/pedido/$numero'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/'
    | '/api/admin/comprovante/$pedidoId'
    | '/api/public/documento/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  PedidoNumeroRoute: typeof PedidoNumeroRoute
  ApiAdminComprovantePedidoIdRoute: typeof ApiAdminComprovantePedidoIdRoute
  ApiPublicDocumentoNumeroRoute: typeof ApiPublicDocumentoNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido/$numero': {
      id: '/pedido/$numero'
      path: '/pedido/$numero'
      fullPath: '/pedido/$numero'
      preLoaderRoute: typeof PedidoNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/igrejas': {
      id: '/admin/igrejas'
      path: '/igrejas'
      fullPath: '/admin/igrejas'
      preLoaderRoute: typeof AdminIgrejasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/api/public/documento/$numero': {
      id: '/api/public/documento/$numero'
      path: '/api/public/documento/$numero'
      fullPath: '/api/public/documento/$numero'
      preLoaderRoute: typeof ApiPublicDocumentoNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/comprovante/$pedidoId': {
      id: '/api/admin/comprovante/$pedidoId'
      path: '/api/admin/comprovante/$pedidoId'
      fullPath: '/api/admin/comprovante/$pedidoId'
      preLoaderRoute: typeof ApiAdminComprovantePedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminPedidosRouteChildren {
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

interface AdminRouteChildren {
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminIgrejasRoute: typeof AdminIgrejasRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminIgrejasRoute: AdminIgrejasRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  PedidoNumeroRoute: PedidoNumeroRoute,
  ApiAdminComprovantePedidoIdRoute: ApiAdminComprovantePedidoIdRoute,
  ApiPublicDocumentoNumeroRoute: ApiPublicDocumentoNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
