-- Importa as igrejas da planilha "Tutte le Localita.xlsx" (aba Localita),
-- agrupadas por localidade. A localidade fica em igrejas.regiao (texto livre),
-- entao removemos o antigo check norte/centro/sul. O codigo interno vai em cidade.

ALTER TABLE public.igrejas DROP CONSTRAINT IF EXISTS igrejas_regiao_check;

-- Remove as igrejas de exemplo criadas no seed inicial.
DELETE FROM public.igrejas WHERE nome IN ('CCI Sede','CCI Filial Norte','CCI Filial Sul');

INSERT INTO public.igrejas (nome, cidade, regiao, ativo) VALUES
  ('BARONISSI (SALERNO)', '01-0011', 'BELVEDERE', true),
  ('BELVEDERE MARITTIMO', '01-0002', 'BELVEDERE', true),
  ('BELVEDERE MARITTIMO - MALAFARINA', '01-0003', 'BELVEDERE', true),
  ('CERENZIA', '01-0055', 'BELVEDERE', true),
  ('CHORIO', '01-0007', 'BELVEDERE', true),
  ('GUARDIA PIEMONTESE', '01-0062', 'BELVEDERE', true),
  ('LIONI', '01-0009', 'BELVEDERE', true),
  ('STATTE (TARANTO)', '01-0041', 'BELVEDERE', true),
  ('TRENTOLA DUCENTA (AVERSA)', '01-0010', 'BELVEDERE', true),
  ('ALTEDO (BOLOGNA)', '01-0012', 'CODOGNO', true),
  ('BARBERINO VAL D''ELSA (SIENA)', '01-0063', 'CODOGNO', true),
  ('BIANZONE (SONDRIO)', '01-0064', 'CODOGNO', true),
  ('BUSTO ARSIZIO', '01-0042', 'CODOGNO', true),
  ('CODOGNO', '01-0014', 'CODOGNO', true),
  ('COLLECCHIO (PARMA)', '01-0013', 'CODOGNO', true),
  ('FIRENZE', '01-0030', 'CODOGNO', true),
  ('GENOVA', '01-0017', 'CODOGNO', true),
  ('INVERIGO', '01-0060', 'CODOGNO', true),
  ('LODI', '01-0052', 'CODOGNO', true),
  ('PIACENZA', '01-0045', 'CODOGNO', true),
  ('PORTOFERRAIO (ISOLA D''ELBA)', '01-0050', 'CODOGNO', true),
  ('SESTO SAN GIOVANNI (MILANO)', '01-0019', 'CODOGNO', true),
  ('TORRE BOLDONE (BERGAMO)', '01-0048', 'CODOGNO', true),
  ('DUEVILLE', '01-0035', 'DUEVILLE', true),
  ('FERRARA', '01-0066', 'DUEVILLE', true),
  ('OPPEANO (VERONA)', '01-0036', 'DUEVILLE', true),
  ('RONCADE', '01-0059', 'DUEVILLE', true),
  ('SAN GIORGIO BIGARELLO (MANTOVA)', '01-0018', 'DUEVILLE', true),
  ('TRENTO', '01-0068', 'DUEVILLE', true),
  ('TRIESTE', '01-0065', 'DUEVILLE', true),
  ('AOSTA', '01-0031', 'PIANEZZA', true),
  ('BEINETTE (MONDOVI)', '01-0022', 'PIANEZZA', true),
  ('BIELLA', '01-0058', 'PIANEZZA', true),
  ('PIANEZZA (TORINO)', '01-0023', 'PIANEZZA', true),
  ('SPINETTA MARENGO (ALESSANDRIA)', '01-0021', 'PIANEZZA', true),
  ('MESSINA', '01-0025', 'RAGUSA', true),
  ('PALERMO', '01-0061', 'RAGUSA', true),
  ('PALERMO (COSTRUZIONE)', '', 'RAGUSA', true),
  ('RAGUSA', '01-0038', 'RAGUSA', true),
  ('CAMPOBASSO - PETRELLA TIFERNINA', '01-0020', 'TERAMO', true),
  ('FROSINONE', '01-0067', 'TERAMO', true),
  ('ROMA', '01-0015', 'TERAMO', true),
  ('ROSETO DEGLI ABRUZZI', '01-0049', 'TERAMO', true),
  ('SPOLTORE (PESCARA)', '01-0001', 'TERAMO', true),
  ('TERAMO', '01-0051', 'TERAMO', true);
